### ISSUE TITLE
Do not remove facilities from acknowledgements

### ISSUE THREAD

**Issue by marblestation** [adsabs/ADSfulltext#100]
We are removing facilities from acknowledgements: https://github.com/adsabs/ADSfulltext/blob/d2fcdcac7d9af2f7f3f292106fc21d4ab90a3b2b/adsft/extraction.py#L715-L717
but this information is useful to be kept there so that users that search the ack field can find the facilities (if that's what they are looking for). I think it would be good to extract the facilities without removing them from the acknowledgment.

**Comment by krisbukovi** [comment]
For clarification: If we have a facility field available for users to search for in the future, would we want to revert this change? Or do we always want the facilities in the acknowledgments field regardless of that capability?
