### ISSUE TITLE
Wiley seperation of acknowledgements from body content

### ISSUE THREAD

**Issue by jonnybazookatone** [adsabs/ADSfulltext#18]
Hi Jonny,

Didn't know where to create an issue for this, so I'm just letting you know about it. It looks like the XML parser for content we got from Wiley is not working as well as it should. As an example, see the parsed content from 2012MNRAS.419.3018C, which is in /proj/ads/articles/fulltext/extracted/20/12/MN/RA/S,/41/9,/30/18/C/

The fulltext clearly includes all of the acknowledgments as well as the bibliography, as a result that the acknowledgements are defined _within_ the <body></body> tags.

**Comment by krisbukovi** [comment]
The fulltext for 2012MNRAS.419.3018C and other articles where the acknowledgements are nested within the body tag are now extracted without the acknowledgements and bibliography included.
