### ISSUE TITLE
Fulltext extraction problem?

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/ADSfulltext#22]
This query returns 0 results for some reason.  Can you please figure out where things break down?

```
bibcode:2015ApJ...801..127V body:DAOPHOT
```

**Comment by jonnybazookatone** [comment]
This does not return anything as DAOPHOT is within the appendix of the file, and not the full text 'body' content.

I will close this ticket and open another ticket related to how to tackle the extraction of the appendix. See issue #23.
