### ISSUE TITLE
Fix missing appendix text

### ISSUE THREAD

**Issue by spacemansteve** [adsabs/ADSfulltext#73]
A user reports they cannot search for text in the appendix portion for 2012A&A...539A..88C.  For at least some types of xml files we are not extracting text from appendices and appending to the body field.  For another example see 2012A&A...539A.119F.  

For at least some pdf files, we do extract text from appendices and append it to the body field.

**Comment by spacemansteve** [comment]
These files have an ```<app-group>``` section, perhaps it is being ignored.  For example, see ```/proj/ads/fulltext/sources/A+A/0539/aa17927-11.xml```.

**Comment by aaccomazzi** [comment]
See also #23
